apiVersion: v1
kind: ConfigMap
metadata:
  name: ostad-app-config
  namespace: dev
  labels:
    app: ostad-capstone
    environment: dev
data:
  NODE_ENV: "development"
  API_URL: "http://ostad-capstone-dev.local"
  THEME_INDEX: "0"  # Yellow theme for dev
  LOG_LEVEL: "debug"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ostad-capstone-dev
  namespace: dev
  labels:
    app: ostad-capstone
    environment: dev
    version: v1.0.0
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: ostad-capstone
      environment: dev
  template:
    metadata:
      labels:
        app: ostad-capstone
        environment: dev
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: ostad-app
        image: ostad-capstone:dev-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: ostad-app-config
              key: NODE_ENV
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: ostad-app-config
              key: API_URL
        - name: THEME_INDEX
          valueFrom:
            configMapKeyRef:
              name: ostad-app-config
              key: THEME_INDEX
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: ostad-app-config
              key: LOG_LEVEL
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: ostad-capstone-dev-service
  namespace: dev
  labels:
    app: ostad-capstone
    environment: dev
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: ostad-capstone
    environment: dev
