---
# Common role handlers

- name: restart ssh
  systemd:
    name: ssh
    state: restarted

- name: restart chrony
  systemd:
    name: chrony
    state: restarted

- name: reload ufw
  ufw:
    state: reloaded
