---
# Handlers for kubernetes_common role
# Ostad Capstone Project - Kubernetes common handlers

- name: restart containerd
  systemd:
    name: containerd
    state: restarted
    daemon_reload: true
  become: true

- name: restart kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: true
  become: true

- name: reload systemd
  systemd:
    daemon_reload: true
  become: true
