# Production Inventory for Ostad Capstone Project
# This file defines the infrastructure provisioned by Terraform

all:
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: "../terraform/keys/ostad-capstone-production-key.pem"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_python_interpreter: /usr/bin/python3
    project_name: "ostad-capstone"
    environment: "production"
    
    # Kubernetes Configuration
    kubernetes_version: "1.28"
    pod_network_cidr: "10.244.0.0/16"
    service_network_cidr: "10.96.0.0/12"
    
    # Monitoring Configuration
    prometheus_version: "2.47.2"
    grafana_version: "10.2.0"
    loki_version: "2.9.2"
    node_exporter_version: "1.6.1"
    
  children:
    kubernetes_cluster:
      children:
        control_plane:
          hosts:
            k8s-master:
              ansible_host: "{{ master_public_ip }}"  # Will be populated from Terraform output
              private_ip: "{{ master_private_ip }}"
              instance_type: "t3.large"
              role: "master"
              
        worker_nodes:
          hosts:
            k8s-worker-1:
              ansible_host: "{{ worker_1_public_ip }}"  # Will be populated from Terraform output
              private_ip: "{{ worker_1_private_ip }}"
              instance_type: "t3.medium"
              role: "worker"
              
            k8s-worker-2:
              ansible_host: "{{ worker_2_public_ip }}"  # Will be populated from Terraform output
              private_ip: "{{ worker_2_private_ip }}"
              instance_type: "t3.medium"
              role: "worker"
    
    monitoring:
      children:
        prometheus_servers:
          hosts:
            k8s-master:
              prometheus_role: "server"
              
        grafana_servers:
          hosts:
            k8s-master:
              grafana_role: "server"
              
        loki_servers:
          hosts:
            k8s-master:
              loki_role: "server"
              
        node_exporters:
          hosts:
            k8s-master:
              node_exporter_role: "exporter"
            k8s-worker-1:
              node_exporter_role: "exporter"
            k8s-worker-2:
              node_exporter_role: "exporter"

    # AWS Resources for Health Check
    aws_resources:
      vars:
        region: "us-east-1"
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
